### ISSUE TITLE
min-cache-ttl 貌似没有用

### ISSUE THREAD

**Issue by maxjove** [aa65535/openwrt-dnsmasq#10]
有的解析值缓存不上.每次都是重新查询. 
root@OpenWrt:~#  time nslookup www.qq.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      www.qq.com
Address 1: ::ffff:111.20.240.155
Address 2: 111.20.240.156
Address 3: 111.20.240.157
Address 4: 111.20.240.154
Address 5: 111.20.240.155
real    0m 6.21s
user    0m 0.00s
sys     0m 0.01s
root@OpenWrt:~#  time nslookup www.qq.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      www.qq.com
Address 1: ::ffff:111.20.240.154
Address 2: 111.20.240.155
Address 3: 111.20.240.154
Address 4: 111.20.240.157
Address 5: 111.20.240.156
real    0m 5.89s
user    0m 0.00s
sys     0m 0.00s
root@OpenWrt:~#  time nslookup www.qq.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      www.qq.com
Address 1: ::ffff:111.20.240.155
Address 2: 111.20.240.156
Address 3: 111.20.240.155
Address 4: 111.20.240.154
Address 5: 111.20.240.157
real    0m 4.78s
user    0m 0.00s
sys     0m 0.02s
请确认是不是漏什么了

**Comment by aa65535** [comment]
不要用 nslookup ，使用 dig 命令确认 TTL
```
# dig www.qq.com

; <<>> DiG 9.9.5-P1 <<>> www.qq.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43029
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.qq.com.			IN	A

;; ANSWER SECTION:
www.qq.com.		3467	IN	A	111.30.132.101

;; Query time: 7 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Jan 31 17:38:19 HKT 2015
;; MSG SIZE  rcvd: 55
```
