### ISSUE TITLE
dnsmasq-full first start dhcp failed when router reboot

### ISSUE THREAD

**Issue by paradislover** [aa65535/openwrt-dnsmasq#11]
opwnwrt-14.07,WDR4300, 安装dnsmasq-full_2.72-4_ar71xx.ipk，在路由器重启后，客户端连接路由器获取不到IPV4地址，使用静态IP地址可以，ssh上去netstat -apun发现dnsmasq没有监听udp的67端口。这时候重新启动dnsmasq，发现开启了udp的67端口监听。有没有什么办法跟踪这个问题？
安装的软件有pdnsd监听端口1053，shadowsocks监听1080端口。
dnsmasq使用的http://sourceforge.net/p/openwrt-dist/wiki/Plan4/配置方法。

1.重新安装dnsmasq-full使用默认配置文件依然不行。
2.安装openwrt源中的dnsmasq，使用默认配置可以正常IPV4的dhcp

**Comment by aa65535** [comment]
有没有设置为自动启动？
可以检查一下系统日志里的错误日志。

**Comment by paradislover** [comment]
把这个勾上就解决了DHCP没有启动的问题，Force DHCP on this network even if another server is detected. 
日志也没看到什么错误，发现勾上后多了下面一行，应该是强制启动了。
Tue Feb  3 08:17:57 2015 daemon.info dnsmasq-dhcp[1236]: read /etc/ethers - 0 addresses

dnsmasq的配置：
no-poll
no-resolv
all-servers
min-cache-ttl=1800
cache-size=5000
server=10.38.116.23
server=10.38.116.24
server=10.68.76.57
server=10.68.76.61
server=127.0.0.1#1053
conf-dir=/etc/dnsmasq.d

1053是pdnsd的端口。

**Comment by aa65535** [comment]
可能同一网段中有其他 DHCP 服务器。
