### ISSUE TITLE
dnsmasq does not create /var/lib/misc

### ISSUE THREAD

**Issue by ferstar** [aa65535/openwrt-dnsmasq#12]
https://dev.openwrt.org/ticket/6076
默认启动失败, 需要在dnsmasq.conf中指定dnsmasq.leases到openwrt默认位置
dhcp-leasefile=/tmp/dnsmasq.leases

**Comment by aa65535** [comment]
默认位置： https://github.com/aa65535/openwrt-dnsmasq/blob/master/files/dhcp.conf#L15
