### ISSUE TITLE
请问下server-custom.conf里的配置规则

### ISSUE THREAD

**Issue by lersh** [aa65535/openwrt-dnsmasq#14]
我现在用ss-tunnel，ipset配合dnsmasq翻墙，server-custom.conf转换自gfwlist
不过貌似gfwlist里有很多正则的写法，比如/^https?:\/\/[^\/]+google\.(.*)/ 这样的，没法完美转换到server-custom.conf
不知道server-custom.conf的配置有没有高级的规则，支持正则或者通配符的？

**Comment by aa65535** [comment]
这个是 dnsmasq 规定的格式，不支持正则或者通配符。

**Comment by lersh** [comment]
非常感谢回答。
另外问下，我看到有的教程写server=/后面有点，有的教程不加点，这个有什么区别吗？

**Comment by aa65535** [comment]
@lersh 加不加都一样，参考 https://www.v2ex.com/t/169242

**Comment by lersh** [comment]
好的，非常感谢！
