### ISSUE TITLE
/etc/init.d/dnsmasq启动脚本有问题

### ISSUE THREAD

**Issue by lersh** [aa65535/openwrt-dnsmasq#15]
我装了最新的dnsmasq-full，bcrm47xx版本，发现启动不了，检查发现似乎是/etc/init.d/dnsmasq启动脚本有问题，缺少start()和stop()
环境：12.09/brcm47xx/generic/
我用自带的替换后正常了

**Comment by lersh** [comment]
aa65535 能否说一下为什么close了，是我哪里做的不对吗？

**Comment by aa65535** [comment]
适用于 trunk 分支，因为你使用的 Openwrt 版本太旧了。

当前使用的是 start_service() stop_service() reload_service() 等函数。

**Comment by aa65535** [comment]
此项目的 patch 已经提交至 dnsmasq 中，所以此项目使用的代码来自 openwrt 官方 https://dev.openwrt.org/browser/trunk/package/network/services/dnsmasq

**Comment by lersh** [comment]
呃，因为我的路由器比较老，只有12.09还有trx可以刷，BB的已经没有对应的刷机包了，所以只能这样将就了。对了，12.09的iptables还不带--to-port，也要自己另装

**Comment by lersh** [comment]
不知道能不能增加一下说明，或者两种函数都兼容呢，不然第一次用的人很头痛啊

**Comment by aa65535** [comment]
本项目提到的特性已经合并到 dnsmasq 新版本中了，所以本项目不打算再维护了。
而 `--ignore-address` 选项在 gfw 升级后也没有使用的意义了，所以旧版本也一样用。

至于不支持 `--to-port` 参数应该是 iptables 模块没安装。

**Comment by lersh** [comment]
好的，谢谢你
