### ISSUE TITLE
noresolv 设置之后发现无效

### ISSUE THREAD

**Issue by zyallday** [aa65535/openwrt-dnsmasq#16]
最近按照大大分享的shadowsocks+chinadns+dnsmasq-full的方案配置FQ，一直没什么问题，可是最近发现有些内网域名没办法解析，通过nslookup 查询hemiwei.com的适合，发现bad address，但是设置通过
223.5.5.5是可以解析的，我在路由下使用nslookup hemiwei.com 114.114.114.114可以查询到ip是192.168.0.106也就是说是正确的，但是 直接使用nslookup hemiwei.com 的适合 是通过 127.0.0.1 去查询的返回 unknown host,按道理设置忽略resolv 不是应该是通过dnsmasq去转发dns请求的吗？求各位大大帮忙看下~~~感激不尽。
下面贴上我的配置：
dhcp
> config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option domain 'lan'
	option expandhosts '1'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option local '127.0.0.1#5353'
	option noresolv '1'
	option nohosts '1'

chinadns
> config chinadns
	option enable '1'
	option compression '1'
	option chnroute '/etc/chinadns_chnroute.txt'
	option port '5353'
	option server '223.5.5.5,127.0.0.1:5300'
	option bidirectional '1'

dnsmasq.conf
> no-poll
no-resolv
all-servers
cache-size=5000
min-cache-ttl=1800
server=127.0.0.1#5300
server=223.5.5.5
conf-dir=/etc/dnsmasq.d

**Comment by aa65535** [comment]
no-resolv 只是让 dnsmasq 不将 /etc/resolv.conf 中设置的 DNS 当作上游服务器而已。

如果你在 LuCI 中设置过就不用再在 /etc/dnsmasq.conf 里面写配置内容。

你在 /etc/dnsmasq.conf 设置了 `server=223.5.5.5` 就无法过滤投毒了。

**Comment by zyallday** [comment]
大大是因为这个public DNS是某宝的缘故吗？ 还是单纯的设置出现问题，谢谢大大回复。

**Comment by aa65535** [comment]
国内DNS都是这个问题。
把你在 dnsmasq.conf 里 server 的设置都删掉就行了。

**Comment by zyallday** [comment]
大大，我改了设置如下：
> config chinadns
	option enable '1'
	option compression '1'
	option chnroute '/etc/chinadns_chnroute.txt'
	option port '5353'
	option bidirectional '0'
	option server '114.114.114.114,127.0.0.1:5300'

> config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option domain 'lan'
	option expandhosts '1'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option noresolv '1'
	option nohosts '1'
	list server '127.0.0.1#5353'

>  dnsmasq.conf
o-poll
no-resolv
all-servers
cache-size=5000
min-cache-ttl=1800
#server=127.0.0.1#5300
#server=223.5.5.5
conf-dir=/etc/dnsmasq.d

可是 通过路由还是没办法 hemiwei.com 的ip 依然bad address

**Comment by zyallday** [comment]
在路由里直接nsloopup hemiwei.com 如下
> root@OpenWrt:~# nslookup hemiwei.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

> nslookup: can't resolve 'www.hemiwei.com': Name or service not known

在路由里指定dns 如下
> root@OpenWrt:~# nslookup hemiwei.com 114.114.114.114
Server:    114.114.114.114
Address 1: 114.114.114.114 public1.114dns.com

> Name:      hemiwei.com
Address 1: 192.168.0.106

配置是上面的配置

**Comment by zyallday** [comment]
Hi,大大
        我发现是因为这个域名解析是内网的原因，如果我把这个域名指向外网的IP就可以解析，这个是什么原因呢？比如我把这个域名A记录设置为114.114.114.114 就可以成功解析 但是如果设置成192.168.0.106 就没办法解析 这个是什么原因呢？

**Comment by aa65535** [comment]
可能是 ChinaDNS 设置的问题，不过你可以通过在 dnsmasq.conf 里面添加一个 server 设置
server=/hemiwei.com/114.114.114.114
这样可以使这个域名通过114DND 查询而不通过 ChinaDNS。

2015年6月10日 20:31于 Desert <notifications@github.com>写道：
Hi,大大
        我发现是因为这个域名解析是内网的原因，如果我把这个域名指向外网的IP就可以解析，这个是什么原因呢？比如我把这个域名A记录设置为114.114.114.114 就可以成功解析 但是如果设置成192.168.0.106 就没办法解析 这个是什么原因呢？

---

**Comment by zyallday** [comment]
这个方式我之前已经试过了 没有作用 听你这么一说 好像真的是使用了ChinaDNS之后 才产生的 我研究下什么原因 多谢大大

**Comment by zyallday** [comment]
大大 我大概找到原因了 
> ifconfig  之后
> eth0.2    Link encap:Ethernet  HWaddr F8:B1:56:CF:D0:F0
          inet addr:192.168.0.115  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::fab1:56ff:fecf:d0f0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4833 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2314 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2179944 (2.0 MiB)  TX bytes:302890 (295.7 KiB)

192.168.0.x这段被eth0.2占用了 所以 dns解析的时候 其实解析到了真实的结果 但是被丢弃了结果
