### ISSUE TITLE
dnsmasq-full问题，你能不做LUCI界面？

### ISSUE THREAD

**Issue by dsyo2008** [aa65535/openwrt-dnsmasq#8]
我觉得来改去改，还要重启dnsmasq。。很麻烦。你能做LUCI，有LUCI直接生效很快了，我希望有LUCI界面，确实dnsmasq没必要LUCI，但是改很麻烦，有LUCI方便 改完直接生效

**Comment by aa65535** [comment]
还是自己写配置文件里吧，目前不会去考虑做这个，LuCI 有自带的 **网络 - DHCP/DNS** 这个设置页面。
