### ISSUE TITLE
亲，新年好，再次遇到youtube不能播放的问题了，请更新ip list

### ISSUE THREAD

**Issue by hero18688** [aa65535/openwrt-dnsmasq#9]
http://www.v2ex.com/t/156926
https://github.com/clowwindy/ChinaDNS/blob/master/iplist.txt

**Comment by aa65535** [comment]
目前使用 iplist 可能无效果了
clowwindy/ChinaDNS-C#42
https://www.v2ex.com/t/158318

建议使用 ChinaDNS-C https://www.v2ex.com/t/158525

**Comment by hero18688** [comment]
长城宽带禁ping的，这个方法不好用
root@OpenWrt:~# ping 8.8.4.4
PING 8.8.4.4 (8.8.4.4): 56 data bytes
^C
--- 8.8.4.4 ping statistics ---
27 packets transmitted, 0 packets received, 100% packet loss

**Comment by aa65535** [comment]
不需要 ping ，只是跟 8.8.4.4 的延迟，可以使用 dig 一个正常域名得到查询时间。
